apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jobops-tracker.backendName" . }}
  labels:
    {{- include "jobops-tracker.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "jobops-tracker.labels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      enableServiceLinks: false
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "jobops-tracker.backendConfigName" . }}
                  key: APP_NAME
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "jobops-tracker.backendConfigName" . }}
                  key: APP_ENV
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "jobops-tracker.backendConfigName" . }}
                  key: SERVER_PORT
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "jobops-tracker.postgresSecretName" . }}
                  key: DATABASE_URL
          {{- if .Values.backend.probes.enabled }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 8
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jobops-tracker.backendName" . }}
  labels:
    {{- include "jobops-tracker.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
