[jobops_vps]
jobops-demo ansible_host=YOUR_VPS_PUBLIC_IP ansible_user=root

[jobops_vps:vars]
jobops_repo_url=https://github.com/KrishnaTejaCheruku/jobops-tracker.git
jobops_branch=main
jobops_app_dir=/opt/jobops-tracker

# Before domain purchase, use HTTP/IP mode:
jobops_site_address=:80
http_port=80
https_port=443

# After domain purchase, change to:
# jobops_site_address=jobops.yourdomain.com

acme_email=admin@example.com

postgres_db=jobops
postgres_user=jobops
postgres_password=change-this-before-running
