DO $$
BEGIN
    IF current_setting('jobops.allow_dev_test_seed', true) IS DISTINCT FROM 'on' THEN
        RAISE EXCEPTION
            'Refusing to generate dev/test data. Set PGOPTIONS="-c jobops.allow_dev_test_seed=on" to run this seed intentionally.';
    END IF;
END $$;

DELETE FROM users
WHERE email LIKE 'loadtest+%@jobops.local';

WITH generated_users AS (
    INSERT INTO users (email)
    SELECT format('loadtest+%s@jobops.local', lpad(user_number::text, 3, '0'))
    FROM generate_series(1, 100) AS user_number
    RETURNING id, email
),
generated_cv_versions AS (
    INSERT INTO cv_versions (
        user_id,
        name,
        focus_area,
        file_path,
        notes
    )
    SELECT
        id,
        format('Load Test CV %s', substring(email FROM 'loadtest\+([0-9]+)@')),
        'Dev/test generated CV',
        '',
        'Generated by 002_dev_test_bulk_data.sql'
    FROM generated_users
    RETURNING id, user_id, name
)
INSERT INTO applications (
    user_id,
    job_title,
    company_name,
    source,
    job_url,
    location,
    work_mode,
    status,
    cv_version,
    cv_version_id,
    salary_range,
    follow_up_date,
    recruiter_name,
    recruiter_email,
    job_description,
    priority,
    notes,
    applied_date
)
SELECT
    u.id,
    format('Generated Application %s-%s', substring(u.email FROM 'loadtest\+([0-9]+)@'), lpad(application_number::text, 3, '0')),
    format('Generated Company %s', ((application_number - 1) % 25) + 1),
    CASE application_number % 5
        WHEN 0 THEN 'LinkedIn'
        WHEN 1 THEN 'Company Website'
        WHEN 2 THEN 'Recruiter'
        WHEN 3 THEN 'Referral'
        ELSE 'Other'
    END,
    format('https://jobs.example.test/%s/%s', u.id, application_number),
    CASE application_number % 4
        WHEN 0 THEN 'Berlin'
        WHEN 1 THEN 'Remote'
        WHEN 2 THEN 'Hamburg'
        ELSE 'Munich'
    END,
    CASE application_number % 3
        WHEN 0 THEN 'Remote'
        WHEN 1 THEN 'Hybrid'
        ELSE 'On-site'
    END,
    CASE application_number % 9
        WHEN 0 THEN 'Saved'
        WHEN 1 THEN 'Applied'
        WHEN 2 THEN 'Recruiter Contacted'
        WHEN 3 THEN 'Interview Scheduled'
        WHEN 4 THEN 'Technical Interview'
        WHEN 5 THEN 'Offer'
        WHEN 6 THEN 'Rejected'
        WHEN 7 THEN 'Ghosted'
        ELSE 'Withdrawn'
    END,
    cv.name,
    cv.id,
    CASE application_number % 4
        WHEN 0 THEN 'EUR 70k-85k'
        WHEN 1 THEN 'EUR 85k-100k'
        WHEN 2 THEN 'EUR 100k-120k'
        ELSE ''
    END,
    CURRENT_DATE + ((application_number % 15) - 7),
    format('Recruiter %s', application_number),
    format('recruiter-%s@example.test', application_number),
    'Generated dev/test application for load, isolation, analytics, CSV export, and CSV import checks.',
    CASE application_number % 3
        WHEN 0 THEN 'Low'
        WHEN 1 THEN 'Medium'
        ELSE 'High'
    END,
    'Generated by 002_dev_test_bulk_data.sql. Safe to delete.',
    CURRENT_DATE - (application_number % 30)
FROM generated_users u
JOIN generated_cv_versions cv ON cv.user_id = u.id
CROSS JOIN generate_series(1, 100) AS application_number;

DO $$
DECLARE
    generated_user_count INTEGER;
    generated_application_count INTEGER;
    users_with_wrong_application_count INTEGER;
BEGIN
    SELECT COUNT(*)
    INTO generated_user_count
    FROM users
    WHERE email LIKE 'loadtest+%@jobops.local';

    SELECT COUNT(*)
    INTO generated_application_count
    FROM applications a
    JOIN users u ON u.id = a.user_id
    WHERE u.email LIKE 'loadtest+%@jobops.local';

    SELECT COUNT(*)
    INTO users_with_wrong_application_count
    FROM (
        SELECT u.id, COUNT(a.id) AS application_count
        FROM users u
        LEFT JOIN applications a ON a.user_id = u.id
        WHERE u.email LIKE 'loadtest+%@jobops.local'
        GROUP BY u.id
        HAVING COUNT(a.id) <> 100
    ) mismatched_users;

    IF generated_user_count <> 100 THEN
        RAISE EXCEPTION 'Expected 100 generated users, found %', generated_user_count;
    END IF;

    IF generated_application_count <> 10000 THEN
        RAISE EXCEPTION 'Expected 10000 generated applications, found %', generated_application_count;
    END IF;

    IF users_with_wrong_application_count <> 0 THEN
        RAISE EXCEPTION 'Expected every generated user to own exactly 100 applications, found % mismatched users',
            users_with_wrong_application_count;
    END IF;
END $$;
