ALTER TABLE applications
    ADD COLUMN IF NOT EXISTS salary_range TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS follow_up_date DATE,
    ADD COLUMN IF NOT EXISTS recruiter_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS recruiter_email TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS job_description TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS priority TEXT NOT NULL DEFAULT 'Medium';
